kestra:
  server-type: STANDALONE
  repository:
    type: postgres
  queue:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  server:
    basic-auth:
      enabled: false
    host: "0.0.0.0"
    port: ${PORT:-8080}

datasources:
  postgres:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver 
  server-type: STANDALONE
  repository:
    type: postgres
  queue:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  server:
    basic-auth:
      enabled: false
    host: "0.0.0.0"
    port: ${PORT:-8080}

datasources:
  postgres:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver