volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local
  tmp-data:
    driver: local

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  kestra:
    build: .
    environment:
      MICRONAUT_CONFIG_FILES: /app/confs/application.yml
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - kestra-data:/app/storage
      - tmp-data:/tmp/kestra-wd
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
